
-- Enable UUID extension
create extension if not exists "pgcrypto";

-- USERS TABLE
create table if not exists public.users (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  phone text,
  photo_url text,
  type text check (type in ('admin', 'buyer', 'seller', 'farmer', 'agent')),
  merchant_id text,
  messaging_enabled boolean default true,
  network text,
  created_at timestamptz default now()
);

-- MARKETPLACE
create table if not exists public.marketplace (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id),
  seller_name text, -- Cache name for speed
  seller_phone text,
  seller_email text,
  title text,
  category text,
  price numeric,
  usage_instructions text, -- Description
  storage_recommendations text,
  location_name text,
  location_lat float,
  location_lng float,
  image_url text, -- legacy
  image_urls text[], -- array of urls
  created_at timestamptz default now()
);

-- EQUIPMENT
create table if not exists public.equipment (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id),
  owner text, -- Cache name
  name text,
  type text,
  description text,
  location text,
  location_lat float,
  location_lng float,
  price_per_day numeric,
  image_url text,
  image_urls text[],
  available boolean default true,
  created_at timestamptz default now()
);

-- TRANSACTIONS
create table if not exists public.transactions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id),
  amount numeric,
  currency text default 'GHS',
  type text, -- DEPOSIT, WITHDRAWAL, LOAN, PAYMENT, TRANSFER
  status text, -- pending, completed, failed
  provider text, -- MTN, Bank
  provider_reference text,
  phone_number text,
  description text,
  created_at timestamptz default now()
);

-- CHATS (Messaging)
create table if not exists public.chats (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.users(id),
  receiver_id uuid references public.users(id),
  item_id text, -- ID of the item being discussed (Market or Equipment)
  message_text text,
  is_read boolean default false,
  created_at timestamptz default now()
);

-- INQUIRIES (Formal requests)
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id), -- Sender
  recipient_id uuid references public.users(id),
  item_id text,
  item_type text,
  name text,
  email text,
  phone text,
  message text,
  subject text,
  status text default 'pending',
  created_at timestamptz default now()
);

-- FORUM POSTS
create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id),
  author text,
  title text,
  content text,
  image_url text,
  images text[],
  replies jsonb default '[]'::jsonb, -- Storing replies as JSON for simplicity
  created_at timestamptz default now()
);

-- USER REVIEWS
create table if not exists public.user_reviews (
  id bigint generated by default as identity primary key,
  reviewer_id uuid references public.users(id),
  target_user_id uuid references public.users(id),
  rating integer check (rating >= 1 and rating <= 5),
  comment text,
  created_at timestamptz default now()
);

-- USER FILES (Pest diagnosis images, etc)
create table if not exists public.user_files (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.users(id),
  file_url text,
  storage_path text,
  file_name text,
  file_type text,
  context text,
  ai_summary text,
  notes text,
  created_at timestamptz default now()
);

-- MARKETPLACE LIKES
create table if not exists public.marketplace_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id),
  item_id uuid references public.marketplace(id),
  created_at timestamptz default now(),
  unique(user_id, item_id)
);

-- SETTINGS (Global App Config, Ad Banners)
create table if not exists public.settings (
  id text primary key,
  value jsonb
);

-- Row Level Security (RLS) Setup
alter table public.users enable row level security;
alter table public.marketplace enable row level security;
alter table public.equipment enable row level security;
alter table public.transactions enable row level security;
alter table public.chats enable row level security;
alter table public.inquiries enable row level security;
alter table public.forum_posts enable row level security;
alter table public.user_reviews enable row level security;
alter table public.user_files enable row level security;
alter table public.marketplace_likes enable row level security;
alter table public.settings enable row level security;

-- POLICIES (Simplified for Demo - In Production, tighten these)

-- USERS: Public read, Self update
create policy "Public users are viewable by everyone" on public.users for select using (true);
create policy "Users can insert their own profile" on public.users for insert with check (auth.uid() = id);
create policy "Users can update own profile" on public.users for update using (auth.uid() = id);

-- MARKETPLACE: Public read, Authenticated create/update/delete
create policy "Marketplace items are public" on public.marketplace for select using (true);
create policy "Auth users can create items" on public.marketplace for insert with check (auth.role() = 'authenticated');
create policy "Users manage own items" on public.marketplace for update using (auth.uid() = user_id);
create policy "Users delete own items" on public.marketplace for delete using (auth.uid() = user_id);

-- EQUIPMENT: Similar to Marketplace
create policy "Equipment items are public" on public.equipment for select using (true);
create policy "Auth users can create equipment" on public.equipment for insert with check (auth.role() = 'authenticated');
create policy "Users manage own equipment" on public.equipment for update using (auth.uid() = user_id);
create policy "Users delete own equipment" on public.equipment for delete using (auth.uid() = user_id);

-- TRANSACTIONS: Private to user
create policy "Users view own transactions" on public.transactions for select using (auth.uid() = user_id);
create policy "Users create transactions" on public.transactions for insert with check (auth.uid() = user_id);

-- CHATS: Private between sender and receiver
create policy "Users view their chats" on public.chats for select using (auth.uid() = sender_id or auth.uid() = receiver_id);
create policy "Users send chats" on public.chats for insert with check (auth.uid() = sender_id);
create policy "Users update chats" on public.chats for update using (auth.uid() = receiver_id); -- e.g. mark as read

-- SETTINGS: Public read, Admin only update (Mocking admin check via simple boolean or just allowing auth for demo)
create policy "Settings are public" on public.settings for select using (true);
create policy "Authenticated can update settings" on public.settings for insert with check (auth.role() = 'authenticated');
create policy "Authenticated can update settings values" on public.settings for update using (auth.role() = 'authenticated');

-- STORAGE BUCKET SETUP (If not exists)
insert into storage.buckets (id, name, public) values ('user_uploads', 'user_uploads', true) on conflict do nothing;

create policy "Public Access" on storage.objects for select using ( bucket_id = 'user_uploads' );
create policy "Auth Upload" on storage.objects for insert with check ( bucket_id = 'user_uploads' and auth.role() = 'authenticated' );
create policy "Owner Delete" on storage.objects for delete using ( bucket_id = 'user_uploads' and auth.uid() = owner );
